name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy
        run: npm run deploy
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
          MAILRU_CLIENT_ID: ${{ secrets.MAILRU_CLIENT_ID }}
          MAILRU_SECRET: ${{ secrets.MAILRU_SECRET }}
          YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
          YANDEX_SECRET: ${{ secrets.YANDEX_SECRET }}
          VK_CLIENT_ID: ${{ secrets.VK_CLIENT_ID }}
          VK_CLIENT_SECRET: ${{ secrets.VK_CLIENT_SECRET }}
